---

# Docker compose file used for LPRRs Jenkins environment

version: "3.7"
services:
  swtools:
    volumes:
      - ./id_rsa:/home/developer/.ssh/id_rsa
      - ./known_hosts:/home/developer/.ssh/known_hosts
